Add support for customisation scripts
OddBloke/ubuntu-standalone-builder pull request #6
Opened 2017-01-25 17:10 UTC by OddBloke

2017-01-25 18:11 UTC, josvazg commented
LGTM!

Code seems fine and:

========================================================================================== 17 passed in 0.20 seconds ==========================================================================================
___________________________________________________________________________________________________ summary ___________________________________________________________________________________________________
  py27: commands succeeded
  py35: commands succeeded
  congratulations :)

2017-01-25 18:18 UTC, josvazg approved these changes
LGTM!
And tests pass!

2017-01-26 02:07 UTC, rcj4747 requested changes
Finding the execution of their custom script will be a chore the first time.  Let's have our example show use of 'set -x' and an 'echo' to say that we've arrived.

2017-01-26 02:07 UTC, rcj4747 commented on README.md
> +#!/bin/sh
I would suggest adding "-x" to match the other output the user will see.

Also an echo won't hurt as an example of a good practice to say we're here.  The build output will have no delimiter saying that it's executing this hook so debugging will be harder for the end user without some breadcrumbs.

`echo "======================== Running customization script ==========================="`

2017-01-26 02:08 UTC, rcj4747 commented on README.md
> +#!/bin/sh
After that I'm +1.  The tests pass and images boot (I tested disk1).

2017-01-26 03:08 UTC, rcj4747 commented on generate_build_config.py
> +- encoding: b64
I was going to suggest gz+b64 as some clouds we have seen have relatively low limits on the size of user-data.  However, I don't know of a python 2/3 compatible way to do that.  Python2 uses gzip.GzipFile on a StringIO object but Python3 would need to use io.BytesIO.

I was going to suggest (for python2):

```
     if customisation_script is not None:
         with open(customisation_script, 'rb') as f:
-            content = base64.b64encode(f.read()).decode('utf-8')
+            content_gz = StringIO.StringIO()
+            with gzip.GzipFile(fileobj=content_gz, mode='w') as fgz:
+                fgz.write(f.read())
+            content = base64.b64encode(content_gz.getvalue()).decode('utf-8')
         if content:
             output_string += '\n'
```

2017-01-26 03:21 UTC, rcj4747 commented on generate_build_config.py
> +- encoding: b64
I figured it out, thoughts?

```
diff --git a/generate_build_config.py b/generate_build_config.py
index a1e39e1..834628a 100755
--- a/generate_build_config.py
+++ b/generate_build_config.py
@@ -1,7 +1,12 @@
 #!/usr/bin/env python
 from __future__ import print_function
 
+try:
+    from StringIO import StringIO as IO
+except:
+    from io import BytesIO as IO
 import base64
+import gzip
 import sys
 
 
@@ -36,7 +41,7 @@ runcmd:
 
 WRITE_FILES_TEMPLATE = """\
 write_files:
-- encoding: b64
+- encoding: gz+b64
   content: {content}
   path:
     /home/ubuntu/build-output/chroot-autobuild/usr/share/livecd-rootfs/live-build/ubuntu-cpc/hooks/9999-local-modifications.chroot
@@ -55,7 +60,10 @@ def _write_cloud_config(output_file, customisation_script=None):
     output_string = TEMPLATE
     if customisation_script is not None:
         with open(customisation_script, 'rb') as f:
-            content = base64.b64encode(f.read()).decode('utf-8')
+            content_gz = IO()
+            with gzip.GzipFile(fileobj=content_gz, mode='w') as fgz:
+                fgz.write(f.read())
+            content = base64.b64encode(content_gz.getvalue()).decode('utf-8')
         if content:
             output_string += '\n'
             output_string += WRITE_FILES_TEMPLATE.format(content=content)
```

2017-01-26 03:22 UTC, rcj4747 commented on generate_build_config.py
> +- encoding: b64
And I can't find the user-data metadata limit for Azure as that's the cloud used in the example.  Practically speaking I don't think their limit is all that low (16K maybe?).

2017-01-26 03:25 UTC, rcj4747 commented on generate_build_config.py
> +- encoding: b64
And this can be another PR.  My abstention for this PR is the example customization script comments only.

2017-01-26 14:50 UTC, chrisglass commented on generate_build_config.py
>          The path for the file to write to.
A :param entry for customisation_script is missing here.

2017-01-26 14:53 UTC, OddBloke commented on generate_build_config.py
>          The path for the file to write to.
Fixed.

2017-01-26 14:58 UTC, rcj4747 approved these changes

2017-01-26 14:59 UTC, merged